config/routes.rb
Rails.application.routes.draw do
  
  #admin route
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #devise all route
  devise_for :users

  #Devise set root page for localhost:3000
  devise_scope :user do 
    authenticated :user do 
      root to: "projects#index"
    end
    unauthenticated :user do
      root to: "devise/sessions#new"
    end
  end

  #project Routes 
  resources :projects

  # Task Custom Route 
  resources :tasks
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    def index
    #   @projects = Projects.all
    #   p @projects
    #   p 1111111111111111111111111
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # before_action :all_tasks, only: [:index, :create]
  # respond_to :html, :js
  
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new 
  end

  def create
    @project = Project.new(project_params)
    @project.save
    redirect_to @project
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    @project.update(product_params)
    redirect_to projects_path
  end

  def show
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to @project
  end

  private
  def project_params
    params.require(:project).permit(:p_name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    # @tasks = Task.all
    project = Project.find_by(id: params[:project_id])
    @tasks = project.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    @tasks = Project.find_by(id: task_params[:project_id]).tasks
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(task_params)
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:t_name, :description, :p_name, :project_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/blogs/index.html.erb
<<<<<<< HEAD
<h1>project List </h1>
=======
</h1> Project List </h1>
>>>>>>> 0e06aa44fa4d11c5206ab9a1cf972103d93f81b4

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if user_signed_in? %>
  <div id="page-content-wrapper">
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
      <button class="btn btn-primary" id="menu-toggle">Toggle Menu</button>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <div class="dropdown-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
                <% else %>
              <% end %>
            </div>
            </div>
          </li>
        </ul>
      </div>
      </div>
    </nav>
  <%=yield %>
  </body>
</html>

app/views/projects/_fill.html.erb
<h1> Enter Detail</h1>

<%= form_for @project, method: :post, remote: true do |form| %>
    <p>
        <%= form.label :project_name %><br>
        <%= form.text_field :p_name %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/projects/edit.html.erb
<%= render 'fill'%>

app/views/projects/index.html.erb
<div class="d-flex" id="wrapper">
  <!-- Sidebar -->
  <div class="bg-light border-right" id="sidebar-wrapper">
    <div class="sidebar-heading">Start Bootstrap </div>
    <div class="list-group list-group-flush">
      <% @projects.each do |p|%>
        <li class="list-group-item list-group-item-action bg-light">
          <%= link_to p.p_name, tasks_path(project_id: p.id), remote: true %>
        </li>
      <%end%>
    </div>
    </div>
    
  <div class="container-fluid">
    <h1 class="mt-4">Simple Sidebar</h1>
      <div id="taskList"></div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<<<<<<< HEAD
<%= form_with(model: @project, local: true) do |form| %>
    
  <%= form.label :Name %>
  <%= form.text_field :p_name %>

  <%= form.submit %>
<%end%>



=======
<%= render 'fill'%>
>>>>>>> 0e06aa44fa4d11c5206ab9a1cf972103d93f81b4

app/views/projects/show.html.erb
    <strong> Name </strong>
    <%= @project.p_name %><br>

    

<%= link_to 'Back', projects_path %>

app/views/tasks/_index.html.erb
<table class="table">
  <thead class="thead-light">
    <tr class="table-danger">
      <td> Task Name</td>
      <td> Edit Task</td>
      <td> Show Task</td>
      <td> Delete Task</td>
    </tr> 
  </thead>

  <div id="task">
    <%= link_to 'New Task', new_task_path, remote: true %>
  </div>
  <tbody id="taskBody">
    <%= render 'task_body' %>
  </tbody>
</table>

app/views/tasks/_task_body.html.erb
<% @tasks.each do|task| %>
  <tr>
    <td><%= task.t_name %></td>
  </tr> 
<% end %>

app/views/tasks/_taskform.html.erb
<h1> Enter Detail</h1>

<%= form_for @task, method: :post, remote: true do |form| %>
    <p>
        <%= form.label :Task_name %><br>
        <%= form.text_field :t_name %>
    </p>
    <p>
        <%= form.label :Description %><br>
        <%= form.text_field :description %>
    </p>
    <p>
        <%= form.label :Project_name %><br>
        <%= form.select :project_id, collection: Project.pluck(:p_name, :id) %>
    </p>
    </p>
        <%= form.submit %>
    </p>
<% end %>

app/views/tasks/create.js.erb
$('#taskList').html("<%= j render partial: 'tasks/index' %>")

app/views/tasks/edit.html.erb
<%= render 'taskform'%>

app/views/tasks/index.js.erb
console.log('here');
$('#taskBody').html("<%= j render partial: 'tasks/index' %>")

app/views/tasks/new.html.erb
<%= render 'taskform'%>

app/views/tasks/new.js.erb
$("#taskBody").hide();
$('#taskList').html("<%= j (render 'taskform') %>");

app/views/tasks/show.html.erb
<strong> Task Name </strong>
<%= @task.t_name %><br>

<%= link_to 'Back', tasks_path %>